# Site settings
title: Mohsen Azimi
email: me@azimi.me
description: Mohsen Azimi's personal weblog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://azimi.me" # the base hostname & protocol for your site
twitter_username: "mohsen____"
github_username:  mohsen1

# Build settings
markdown: kramdown
